# Generated by Django 4.2.5 on 2023-09-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='names/', verbose_name='изображение(превью)')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('purchase_price', models.IntegerField(max_length=150, verbose_name='цена за покупку')),
                ('date_creation', models.DateField(max_length=150, verbose_name='дата создания')),
                ('date_last_mod', models.DateField(max_length=150, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
